# action.yml
name: "action-organization-manager"
description: "manager organization repositories in one file"
author: myml
branding:
  icon: align-center
  color: "black"
inputs:
  app_id:
    description: "github app id"
    required: true
  installation_id:
    description: "github app installation id"
    required: true
  private_key:
    description: "github app private key"
    required: true
  config_file:
    description: "manager config file"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.17.1
    - name: install action bin
      shell: bash
      run: |
        cd $GITHUB_ACTION_PATH
        go build
    - name: command
      shell: bash
      run: $GITHUB_ACTION_PATH/action-organization-manager -f=${{ inputs.config_file }} -app_id=${{ inputs.app_id }} -installation_id=${{ inputs.installation_id }}
      env:
        PRIVATE_KEY: ${{ inputs.private_key }}
